apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: microservices-demo
  namespace: microservices-demo
spec:
  promotionPolicies:
    - stageSelector:
        name: uat
      autoPromotionEnabled: true
    - stageSelector:
        name: prod
      autoPromotionEnabled: false