apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: homelab-demo
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: homelab-demo
      sources:
        stages:
          - uat
  promotionTemplate:
    spec:
      steps:
        - uses: argocd-update
          config:
            apps:
              - name: homelab-demo-prod
                namespace: argocd
                sources:
                  - repoURL: https://github.com/iemafzalhassan/homelab.git
                    kustomize:
                      images:
                        - image: homelabacrepb3n6.azurecr.io/homelab-demo
                          tag: ${{ freight.commits[0].id }}
