apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: microservices-demo
  namespace: microservices-demo
spec:
  subscriptions:
    - git:
        repoURL: https://github.com/iemafzalhassan/homelab.git
        branch: main
        includePaths:
          - manifests/apps/microservices-demo/