apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: homelab-demo
  namespace: homelab-demo
spec:
  subscriptions:
    - git:
        repoURL: https://github.com/iemafzalhassan/homelab.git
        branch: main
        includePaths:
          - manifests/apps/homelab-demo/
