apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: microservices-demo
  namespace: microservices-demo
spec:
  subscriptions:
    - git:
        repoURL: https://github.com/GoogleCloudPlatform/microservices-demo.git
        branch: main
        includePaths:
          - kubernetes-manifests/
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
  freightCreationPolicy: Automatic
  interval: 5m0s