apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'oci://ghcr.io/akuity/kargo-charts/kargo'
      chart: kargo
      targetRevision: 1.10.8
      helm:
        valueFiles:
          - $values/manifests/bootstrap/kargo/values.yaml
    - repoURL: 'https://github.com/iemafzalhassan/homelab.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
