apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/iemafzalhassan/homelab.git'
    targetRevision: HEAD
    path: kargo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homelab-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
