apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-extras
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/iemafzalhassan/homelab.git'
    targetRevision: HEAD
    path: manifests/bootstrap/keycloak
    directory:
      include: 'keycloak-httproute.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
