apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      chart: keycloak
      targetRevision: 24.4.2
      helm:
        valueFiles:
          - $values/manifests/bootstrap/keycloak/values.yaml
    - repoURL: 'https://github.com/iemafzalhassan/homelab.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
