apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://oauth2-proxy.github.io/manifests'
      chart: oauth2-proxy
      targetRevision: 7.8.1
      helm:
        valueFiles:
          - $values/manifests/bootstrap/oauth2-proxy/values.yaml
    - repoURL: 'https://github.com/iemafzalhassan/homelab.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: oauth2-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
