apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
    chart: opentelemetry-demo
    targetRevision: 0.40.10
    helm:
      valuesObject:
        default:
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: "metadata.labels['app.kubernetes.io/component']"
            - name: OTEL_COLLECTOR_NAME
              value: "opentelemetry-demo-otelcol"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://k8s-monitoring-alloy-receiver.monitoring.svc:4318"
          schedulingRules:
            tolerations:
              - key: "kubernetes.azure.com/scalesetpriority"
                operator: "Equal"
                value: "spot"
                effect: "NoSchedule"
        prometheus:
          enabled: false
        grafana:
          enabled: false
        jaeger:
          enabled: false
        opentelemetry-collector:
          enabled: true
          config:
            exporters:
              otlphttp/alloy:
                endpoint: "http://k8s-monitoring-alloy-receiver.monitoring.svc:4318"
        components:
          loadgenerator:
            enabled: false
        opensearch:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: otel-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
