apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    app: registry
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: registry
