apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    app: registry
spec:
  replicas: {{ .Values.registry.replicaCount }}
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: "{{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}"
          imagePullPolicy: {{ .Values.registry.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: config
              mountPath: /etc/docker/registry
          env:
            - name: AZURE_STORAGE_ACCOUNT_NAME
              value: "{{ .Values.registry.azure.accountName }}"
            # We expect Workload Identity to provide credentials automatically via env vars
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-registry-config
