package webhooks

import (
	"database/sql"
	"encoding/json"
	"net/http"

	_ "github.com/lib/pq"
	"go.uber.org/zap"
)

// Event describes an event generated by the registry.
type Event struct {
	ID        string `json:"id"`
	Timestamp string `json:"timestamp"`
	Action    string `json:"action"`
	Target    struct {
		MediaType  string `json:"mediaType"`
		Size       int64  `json:"size"`
		Digest     string `json:"digest"`
		Length     int64  `json:"length"`
		Repository string `json:"repository"`
		URL        string `json:"url"`
		Tag        string `json:"tag"`
	} `json:"target"`
	Request struct {
		ID        string `json:"id"`
		Addr      string `json:"addr"`
		Host      string `json:"host"`
		Method    string `json:"method"`
		UserAgent string `json:"useragent"`
	} `json:"request"`
	Actor struct {
		Name string `json:"name"`
	} `json:"actor"`
}

type NotificationEnvelope struct {
	Events []Event `json:"events"`
}

type RegistryHandler struct {
	logger *zap.SugaredLogger
	db     *sql.DB
}

func NewRegistryHandler(logger *zap.SugaredLogger, dbURL string) (*RegistryHandler, error) {
	db, err := sql.Open("postgres", dbURL)
	if err != nil {
		return nil, err
	}
	return &RegistryHandler{
		logger: logger,
		db:     db,
	}, nil
}

func (h *RegistryHandler) HandleEvent(w http.ResponseWriter, r *http.Request) {
	var envelope NotificationEnvelope
	if err := json.NewDecoder(r.Body).Decode(&envelope); err != nil {
		h.logger.Errorw("failed to decode webhook", "error", err)
		http.Error(w, "Bad Request", http.StatusBadRequest)
		return
	}

	for _, event := range envelope.Events {
		h.logger.Infow("received registry event",
			"action", event.Action,
			"repo", event.Target.Repository,
			"digest", event.Target.Digest,
			"tag", event.Target.Tag)

		if event.Action == "push" {
			// Basic implementation to capture manifest metadata.
			// In a real app we'd need to look up org_id from repo string,
			// upsert repository, and then insert manifest/blob.
			// This is a stub for Phase 2 validation.
			h.logger.Debugw("would insert metadata to DB", "digest", event.Target.Digest)
		}
	}

	w.WriteHeader(http.StatusOK)
}

func (h *RegistryHandler) Close() {
	if h.db != nil {
		_ = h.db.Close()
	}
}
