apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-demo
  namespace: demo-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homelab-demo
  template:
    metadata:
      labels:
        app: homelab-demo
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      nodeSelector:
        kubernetes.azure.com/scalesetpriority: "spot"
      containers:
        - name: web
          image: homelabacrepb3n6.azurecr.io/homelab-demo:placeholder
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
