apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    release: k8s-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: jenkins-controller
  endpoints:
  - port: http
    path: /prometheus/
    interval: 30s
