apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-template.yaml
  - pvc-ollama.yaml
  - pvc-app.yaml
  - ollama.yaml
  - backend.yaml
  - frontend.yaml
  - gateway.yaml
