apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: gpt-researcher
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi # Standard Azure Disk
  resources:
    requests:
      storage: 50Gi
