apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpt-researcher-data
  namespace: gpt-researcher
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 10Gi
